# Generated by Django 4.0.3 on 2022-04-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='email of the individual', max_length=300, unique=True, verbose_name='email'),
        ),
    ]
