# Generated by Django 4.0.3 on 2022-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='app.contact'),
        ),
    ]
